---
- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: install packages 
    package:
      name: 
      - python3-psutil
      - tmux 
      - zsh
      - ripgrep
      - gh

  - name: copy wallpaper file
    copy: 
      src: files/wallpapger.png
      dest: /usr/share/backgrounds/ansible_wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: ubuvm
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible_wallpaper.png'"

  - name: set wallpaper position
    become_user: ubuvm 
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
